name: Kubernetes CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Validate Kubernetes Manifests
      run: |
        echo "Validating YAML files"

    - name: Simulate Kubernetes Deployment
      run: |
        echo "kubectl apply -f namespace.yaml"
        echo "kubectl apply -f mariadb-statefulset.yaml"
        echo "kubectl apply -f wordpress-deployment.yaml"
